//process.nextTick并不属于事件环的一部分，再本轮代码执行后执行
setTimeout(()=>{
    console.log(1);
    Promise.resolve().the(()=>{
        console.log('then');
    })
    process.nextTick(()=>{
        console.log('nextTick');
    })
},0);
setTimeout(()=>{
    console.log(2);
},0);

setTimeout(()=>{
    console.log(1);
},0);
setImmediate(()=>{
    console.log('setImmediate');
})